---
networks:
  database:
    driver: overlay

services:
  mongo-init:
    image: ghcr.io/my-piper/piper:${PIPER_IMAGE_TAG}
    env_file:
      - ../../config/piper.env
    networks:
      - database
    command: ["mongo-migrate"]
    deploy:
      mode: replicated-job
      restart_policy:
        condition: on-failure
        max_attempts: 3