---

version: "3.8"

volumes:
  mongo-data:
    external: true
  redis-data:
    external: true
  storage-data:
    external: true

services:
  backend:
    image: registry.gitlab.com/generative-core/piper/fullstack:${PIPER_IMAGE_TAG}
    env_file:
      - ./config/piper.env
    volumes:
      - storage-data:/app/storage
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

  worker:
    image: registry.gitlab.com/generative-core/piper/fullstack:${PIPER_IMAGE_TAG}
    env_file:
      - ./config/piper.env
    volumes:
      - storage-data:/app/storage
    working_dir: /app/backend
    command: npm run worker
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

  periodic:
    image: registry.gitlab.com/generative-core/piper/fullstack:${PIPER_IMAGE_TAG}
    env_file:
      - ./config/piper.env
    volumes:
      - storage-data:/app/storage
    working_dir: /app/backend
    command: npm run periodic
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis/redis-stack
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.25.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
      - storage-data:/var/www/storage:ro
    ports:
      - "80:80"
    healthcheck:
      test: service nginx status || exit 1
      interval: 2s
      retries: 10
      start_period: 5s
      timeout: 5s

  imgproxy:
    image: darthsim/imgproxy:v3.18.2
    environment:
      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/data
    volumes:
      - storage-data:/data/storage:ro

  mysql:
    image: mysql:8.0.33
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
      - ./config/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    env_file:
      - ./config/mysql/config.env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 20s
      retries: 10

  wordpress:
    image: wordpress:6.2.2
    env_file:
      - ./config/wordpress/config.env
    volumes:
      - ${WORDPRESS_VOLUME}:/var/www/html
      - ./config/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
