---

version: "3.8"

volumes:
  mongo-data:
    external: true
  redis-data:
    external: true
  kafka-data:
    external: true
  clickhouse-data:
    external: true
  clickhouse-logs:
    external: true
  storage-data:
    external: true
  prometheus-data:

networks:
  monitoring:

services:
  backend:
    image: registry.gitlab.com/generative-core/piper/fullstack:${PIPER_IMAGE_TAG}
    networks:
      - monitoring
      - default   
    env_file:
      - ./config/piper.env
    volumes:
      - storage-data:/app/storage
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

  worker:
    image: registry.gitlab.com/generative-core/piper/fullstack:${PIPER_IMAGE_TAG}
    networks:
      - monitoring
      - default   
    env_file:
      - ./config/piper.env
    volumes:
      - storage-data:/app/storage
    working_dir: /app/backend
    command: npm run worker
    healthcheck:
      test: curl --fail http://localhost:5555/metrics || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    deploy:
      labels:
        - "prometheus-port=5555"
        - "prometheus-job=piper-worker"
      resources:
        limits:
          memory: 4G
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

  periodic:
    image: registry.gitlab.com/generative-core/piper/fullstack:${PIPER_IMAGE_TAG}
    networks:
      - monitoring
      - default
    env_file:
      - ./config/piper.env
    volumes:
      - storage-data:/app/storage
    working_dir: /app/backend
    command: npm run periodic
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

  sockets:
    image: registry.gitlab.com/generative-core/piper/fullstack:${PIPER_IMAGE_TAG}
    networks:
      - monitoring
      - default
    env_file:
      - ./config/piper.env
    volumes:
      - storage-data:/app/storage
    working_dir: /app/backend
    command: npm run sockets
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

  mongo:
    image: mongo:7.0.11
    networks:
      - monitoring
      - default
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis/redis-stack:7.2.0-v11
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  clickhouse:
    image: clickhouse/clickhouse-server:24.8.4
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/val/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    volumes:
      - kafka-data:/var/lib/kafka/data
    env_file:
      - config/kafka/kafka.env.config

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafka
    ports:
      - "4444:8080"
    env_file:
      - config/kafka/ui.env.config

  nginx:
    image: nginx:1.25.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
      - storage-data:/var/www/storage:ro
    ports:
      - "80:80"
    healthcheck:
      test: service nginx status || exit 1
      interval: 2s
      retries: 10
      start_period: 5s
      timeout: 5s

  imgproxy:
    image: darthsim/imgproxy:v3.18.2
    environment:
      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/data
    volumes:
      - storage-data:/data/storage:ro

  # -- monitoring --
  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./config/promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers
    env_file:
      - config/promtail/promtail.env
    command:
      [
        "-config.file=/etc/promtail/config.yml",
        "-config.expand-env=true"
      ]
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus:v2.44.0
    user: root
    ports:
      - "9090:9090"
    networks:
      - monitoring
    command:
      - '--web.enable-admin-api'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=2w'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      -  prometheus-data:/prometheus/data
      - /var/run/docker.sock:/var/run/docker.sock
    
  exporter-node:
    image: quay.io/prometheus/node-exporter:v1.6.1
    networks:
      - monitoring
    volumes:
      - /:/host:ro,rslave
    command:
      - "--path.rootfs=/host"
      - "--collector.filesystem.mount-points-exclude=^/(etc|boot|run|dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($$|/)"
    ports:
      - "9100:9100"
    deploy:
      mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    networks:
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    command:
      - '-docker_only'
    deploy:
      mode: global
      labels:
         - "prometheus-port=8080"
         - "prometheus-job=cadvisor"

  exporter-redis:
    image: oliver006/redis_exporter:v1.54.0
    networks:
      - monitoring
      - default
    env_file:
      - ./config/exporter_redis.env
    deploy:
      labels:
        - "prometheus-port=9121"
        - "prometheus-job=redis"
      
  exporter-kafka:
    image: danielqsj/kafka-exporter:v1.8.0
    command: ["--kafka.server=kafka:9092"]
    networks:
      - default
      - monitoring
    deploy:
      labels:
        - "prometheus-job=kafka"
        - "prometheus-port=9308"
