global:
  scrape_interval: 10s
  external_labels:
    env: %{ENV}
    project: %{PROJECT}

scrape_configs:
  - job_name: autodiscover
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [ __meta_dockerswarm_task_desired_state ]
        regex: running
        action: keep
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_job ]
        regex: node
        action: drop
      - source_labels: [ __meta_dockerswarm_network_name ]
        regex: piper_monitoring
        action: keep
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_port ]
        regex: .+
        action: keep
      - source_labels: [ __address__, __meta_dockerswarm_service_label_prometheus_port ]
        separator: ":"
        regex: (.+):(.+):(.+)
        replacement: ${1}:${3}
        target_label: __address__
      - source_labels: [ __meta_dockerswarm_service_name ]
        target_label: job
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_job ]
        regex: (.+)
        target_label: job
        replacement: $1
    metric_relabel_configs:
      - regex: container_label_io_confluent_.*
        action: labeldrop
      - regex: container_label_com_docker_.*
        action: labeldrop
      - regex: container_label_maintainer
        action: labeldrop
      - regex: container_label_version
        action: labeldrop
      - regex: container_label_build_date
        action: labeldrop

  - job_name: autodiscover-node
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 9100
        role: tasks
    relabel_configs:
      - source_labels: [ __meta_dockerswarm_task_desired_state ]
        regex: running
        action: keep
      - source_labels: [ __meta_dockerswarm_network_name ]
        regex: piper_monitoring
        action: keep
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_job ]
        regex: node
        action: keep
      - source_labels: [ job ]
        replacement: node
        target_label: job
      - source_labels: [ __meta_dockerswarm_node_hostname ]
        target_label: instance
    metric_relabel_configs:
      - regex: container_label_io_confluent_.*
        action: labeldrop
      - regex: container_label_com_docker_.*
        action: labeldrop
      - regex: container_label_maintainer
        action: labeldrop
      - regex: container_label_version
        action: labeldrop
      - regex: container_label_build_date
        action: labeldrop