server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${CLIENT_URL}

scrape_configs:
  - job_name: piper-backend
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.docker.swarm.service.name=piper_backend"]
    pipeline_stages:
      - json:
          expressions:
            level:
            loggerName:
      - labels:
          level:
      - static_labels:
          env: ${ENV}
          project: ${PROJECT}
          job: piper-backend
  - job_name: piper-worker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.docker.swarm.service.name=piper_worker"]
    pipeline_stages:
      - json:
          expressions:
            level:
            loggerName:
      - labels:
          level:
      - static_labels:
          env: ${ENV}
          project: ${PROJECT}
          job: piper-worker
  - job_name: piper-periodic
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.docker.swarm.service.name=piper_periodic"]
    pipeline_stages:
      - json:
          expressions:
            level:
            loggerName:
      - labels:
          level:
      - static_labels:
          env: ${ENV}
          project: ${PROJECT}
          job: piper-periodic

