---

networks:
  services:
    driver: overlay

volumes:
  gpt4free-cookies:
  gpt4free-images:

services:
  gpt4free:
    image: hlohaus789/g4f:4.0.8
    volumes:
      - gpt4free-cookies:/app/har_and_cookies
      - gpt4free-images:/app/generated_images
    networks:
      - services
