---

networks:
  deno:
    driver: overlay

services:
  deno:
    image: ghcr.io/my-piper/piper-deno:sha-fc30f3a
    networks:
      - deno
    environment:
      - PER_WORKER_MEMORY_MB=128
    deploy:
      replicas: ${DENO_REPLICAS:-5}
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 512m

