---

services:
  imgproxy:
    image: darthsim/imgproxy:v3.18.2
    networks:
      - ingress
    deploy:
      placement:
        constraints:
          -  "node.role==manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.imgproxy.entrypoints=http"
        - "traefik.http.routers.imgproxy.rule=Host(`${DOMAIN}`) && PathPrefix(`/xyz/`)"
        - "traefik.http.services.imgproxy.loadbalancer.server.port=8080"
        - "traefik.docker.network=piper_ingress"
