---

networks:
  monitoring:
    driver: overlay
  database:
    driver: overlay

volumes:
  redis-data:

services:
  redis:
    image: redis/redis-stack:7.4.0-v8
    networks:
      - database
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      placement:
        constraints:
          - node.labels.redis==true

  exporter-redis:
    image: oliver006/redis_exporter:v1.54.0
    networks:
      - monitoring
      - database
    environment:
      - REDIS_ADDR=redis:6379
    deploy:
      labels:
        - "prometheus-port=9121"
        - "prometheus-job=redis"
