---

volumes:
  redis-data:

services:
  redis:
    image: redis/redis-stack:7.2.0-v11
    networks:
      - database
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      placement:
        constraints:
          -  "node.role==manager"

  exporter-redis:
    image: oliver006/redis_exporter:v1.54.0
    networks:
      - monitoring
      - database
    environment:
      - REDIS_ADDR=redis:6379
    deploy:
      labels:
        - "prometheus-port=9121"
        - "prometheus-job=redis"