---

networks:
  database:
    driver: overlay

volumes:
  mongo-data:
  redis-data:
  kafka-data:
  clickhouse-data:
  clickhouse-logs:

services:
  mongo:
    image: mongo:7.0.11
    networks:
      - database
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  exporter-mongo:
    image: percona/mongodb_exporter:0.41.2
    command:
      - "--mongodb.uri=mongodb://mongo:27017"
      - "--compatible-mode"
      - "--discovering-mode"
      - "--collect-all"
    networks:
      - database
      - monitoring
    deploy:
      labels:
        - "prometheus-job=mongo"
        - "prometheus-port=9216"

  redis:
    image: redis/redis-stack:7.2.0-v11
    networks:
      - database
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  exporter-redis:
    image: oliver006/redis_exporter:v1.54.0
    networks:
      - monitoring
      - database
    environment:
      - REDIS_ADDR=redis:6379
    deploy:
      labels:
        - "prometheus-port=9121"
        - "prometheus-job=redis"

  clickhouse:
    image: clickhouse/clickhouse-server:24.8.4
    networks:
      - database
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/val/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    networks:
      - database
    volumes:
      - kafka-data:/var/lib/kafka/data
    env_file:
      - config/kafka/kafka.env.config
        
  exporter-kafka:
    image: danielqsj/kafka-exporter:v1.8.0
    command: ["--kafka.server=kafka:9092"]
    networks:
      - database
      - monitoring
    deploy:
      labels:
        - "prometheus-job=kafka"
        - "prometheus-port=9308"

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    networks:
      - database
    depends_on:
      - kafka
    ports:
      - "4444:8080"
    env_file:
      - config/kafka/ui.env.config
