entryPoints:
  http:
    address: ":80"
  # https:
  #   address: ":443"

providers:
  swarm:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  certresolver:
    acme:
      email: admin@piper.my
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: http

api:
  dashboard: true
  insecure: true

metrics:
  prometheus:
    addServicesLabels: true
    addRoutersLabels: true

      #log:
      #level: DEBUG
