global:
  scrape_interval: 10s
  evaluation_interval: 15s
  external_labels:
    env: ${ENV}
    project: piper-xempire

scrape_configs:
  - job_name: autodiscover
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [ __meta_dockerswarm_task_desired_state ]
        regex: running
        action: keep
      - source_labels: [ __meta_dockerswarm_network_name ]
        regex: piper_monitoring
        action: keep
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_port ]
        regex: .+
        action: keep
      - source_labels: [ __address__, __meta_dockerswarm_service_label_prometheus_port ]
        separator: ":"
        regex: (.+):(.+):(.+)
        replacement: ${1}:${3}
        target_label: __address__
      - source_labels: [ __meta_dockerswarm_service_name ]
        target_label: job
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_job ]
        regex: (.+)
        target_label: job
        replacement: $1

  - job_name: autodiscover-node
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 9100
        role: tasks
    relabel_configs:
      - source_labels: [ __meta_dockerswarm_task_desired_state ]
        regex: running
        action: keep
      - source_labels: [ __meta_dockerswarm_network_name ]
        regex: piper_monitoring
        action: keep
      - source_labels: [ __meta_dockerswarm_service_name ]
        regex: piper_exporter-node
        action: keep
      - source_labels: [ __meta_dockerswarm_node_hostname ]
        target_label: job